name: Build Files for Distribution
on: 
    push:
        branches: ["main"]
    workflow_dispatch:
permissions:
  contents: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.x'
            - name: Install dependencies
              run: |
                  pip install bs4
            - name: Run build script
              run: |
                  python build.py
            - name: Upload built files to latest release
              uses: softprops/action-gh-release@v1
              with:
                  files: dist/index.html
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

           
            